# Database login instructions
username: "bellieny"
hostname: "localhost"
database_name: "caspedia"
port: 5432

# ********* GLOBAL CONFIGURATION *********
# Master table and Genomic context data table
source_metadata_path: ['caspedia_entry_list.csv', 'genomic_context_data.csv']
# Wiki manifest containing URL for each and every wiki intake forms
wiki_manifest_path: "background_data/wiki_manifest.csv"

# DOI Internal database information
doi_table_name: 'doi_citation'
# AddGene Integration table
addgene_schema: 'AddGene'
addgene_table_name: 'summary'
# Sequence Internal Database information
seqrecord_pickle_filename: 'seqrecord_dict'

# Column in the main database that contains unique protein identifiers
unique_id_col: "Type Protein"
# Column in the main database that contains unique protein identifiers
genomic_browser_col: "Browser_Command"
# Column in the Orthologs table holding names of the orthologs
orthologs_name : "Ortholog_Name"

# Sets the name of the sequence browser table name in the PSQL Database
genomic_db_table_name: 'Sequence_Browser'

# Main database table for user input search
default_search_table: "master"
# Genomic context table
genomic_table_name: "genomic"


# ********* TOOL FINDER CONFIGURATION *********
# Translates the options available in the tool finder HTML to
#  column names found in the PSQL database
match_question_to_db:
  "target_type": "Nuclease_Activity"
  "trans_activity": "Nuclease_Activity"
  "targeting_requirement": "Targeting_Requirement"
  "multiplex": "gRNA_and_Multiplexability"

wildcard_search: "Any"

tool_finder_sections:
  - target_type:
      separator: "+"
      field: 0
      format: '<option value="{{ target_type }}">{{ target_type }}</option>'
  - trans_activity:
      separator: "+"
      field: 1
      format: '<option value="{{ trans_activity }}">{{ trans_activity }}</option>'
  - targeting_requirement:
      separator: ""
      field: 0
      format: '<option value="{{ targeting_requirement }}">{{ targeting_requirement }}</option>'
  - multiplex:
      separator: ""
      field: 0
      format: '<option value="{{ multiplex }}">{{ multiplex }}</option>'

# ********* MASTER TABLE CONFIGURATION *********
# In-Database names of source tables
schema: "root"
# Column in the master table that contains the CAS ID
cas_id_col: "Number"
# Column in the master table that contains aa sequence
master_sequence_col: "Protein sequence"
# The column names for the newly imported master table in the PSQL wiki schemas
master_to_wiki_col_names: ["Property", "Info"]
# CasID name order
cas_id_order: ['Nuclease Activity', 'Targeting Requirement', 'gRNA and Multiplexability']

# ********* WIKI CONFIGURATION *********
# The master table is sliced and formatted as an additional table in
#  the Wiki schemas. This is the table name to be used in this import
master_to_wiki_handle: "Classification"
# These are columns that will be imported in the process mentioned above
#   with their respective renaming instructions
master_to_wiki_col_format:
  "Number": "Cas ID"
  "Nuclease_Activity": "Nuclease Activity"
  "Targeting_Requirement": "Targeting Requirement"
  "gRNA_and_Multiplexability": "gRNA and Multiplexability"
  "Class_II_Subtype": "Class 2 subtype"
  "PAM": "PAM"

# The unified message for empty items to be displayed on the wiki page
empty_message: "Not applicable"

# Column name in the wiki forms that denotes raw fasta sequences
wiki_sequence_col_name: "Sequence"
# Path where raw FASTA files will be stored
raw_fasta_path: "/static/fasta/"

# Wiki Pickle Directory path
pickles_path: "static/pkl"
# Wiki page formatting
wiki_template_path: "wiki_template.html"
# Wiki Sheets manifest
links_column: "Curation_Link"
wiki_schema_prefix: "wiki"

# WIKI PFAM instructions
#   The information used to fetch PFAM information will be extracted from the 'Resources' table
#   based on the following row/column:
pfam_source_table: "Resources"
pfam_id_harboring_col: "Value"
pfam_rowname_harboing_col: "Resource"
pfam_source_rowname: "UniProtKB"

# Defines how the pmid and pdb URLs will be formatted in the Uniprot table
uniprot_url_instructions:
  "PubMed_ID": "https://pubmed.ncbi.nlm.nih.gov/"
  "PDB_ID": "https://www.rcsb.org/structure/"
uniprot_url_colname: "Citations"

# Wiki association of table names between PSQL and intake forms
wiki_sections:
  - classification:
      tbl_name: "Classification"
      format: '<li><span style="color: #5758ff;font-weight: bold;">{{ Property }} </span>{{ Info }}</li>'
      n_of_index_cols: 1
  - classification_sprites:
      tbl_name: "Classification_CasID_Sprites"
      format: |
        <img title="{{ Property }}" class="casID_sprite" src="/static/img/cas_id_sprites/{{ Info }}">
      n_of_index_cols: 1
  - properties:
      tbl_name: "Properties"
      format: '<li><span style="color: #5758ff;font-weight: bold;">{{ Property }} </span>{{ Info }} {{ Citations }}</li>'
      n_of_index_cols: 1
  - resources:
      tbl_name: "Resources"
      format: '<li><span style="color: #5758ff;font-weight: bold;">{{ Resource }} </span>{{ Value }}</li>'
      n_of_index_cols: 1
  - sequences:
      tbl_name: "Sequences"
      format: '<li><span style="color: #5758ff;font-weight: bold;">{{ Property }} </span>{{ Link_FASTA }} {{ Citation }}</li>'
      n_of_index_cols: 1
  - text_summaries:
      tbl_name: "Text_Summaries"
      format: |
        '<h3 class="section-header">{{ SECTION }}</h3>
        <p>{{ CONTENT }}</p>'
        {{ ADDGENE_ENTRY }}
      n_of_index_cols: 1
  - exp_details:
      tbl_name: "Experimental_Details"
      format: '' #Directly displayed as a table
      n_of_index_cols: 2
  - gene_editing:
      tbl_name: "Gene_Editing_Examples"
      format: '<h5>{{ Application_Type }}</h5>
                 <ul>
                   <li class="ul-ul"> Description:</li>
                   <span>{{ Description }} {{ Citation_or_Publications }}</span>
                 </ul>'
      n_of_index_cols: 1
  - tools:
      tbl_name: "Tools_And_Diagnostics"
      format: '<h5>{{ Tool_Type }}</h5>
              <ul>
                  <li><span>{{ Tool_Name }}</span></li>
                <ul>
                  <li class="ul-ul"> Description:</li>
                  <span>{{ Description }} {{ Citation }}</span>
                </ul>
              </ul>'
      n_of_index_cols: 1
  - orthologs:
      tbl_name: "Orthologs"
      format: '' # This section's format is a table directly taken from the DB
      n_of_index_cols: 0
  - variants:
      tbl_name: "Engineered_Variants"
      format: '<h5>{{ Variant_Name }}</h5>
              <ul>
                <li class="ul-ul"> Description:</li>
                <span>{{ Description }}</span>
              </ul>'
      n_of_index_cols: 1
  - sequence_browser:
      tbl_name: "Sequence_Browser"
      format: |
        <script type="module">
              import igv from "https://cdn.jsdelivr.net/npm/igv@2.15.8/dist/igv.esm.min.js"
              const options = {{ Browser_Command }};
              igv.createBrowser(document.getElementById("container"), options);
          </script>
      n_of_index_cols: 0
  - pfam:
      tbl_name: "PFAM_Domains"
      format: '' #Directly displayed as a table
      n_of_index_cols: 1
  - domains:
      tbl_name: "Protein_Regions"
      format: '' #Directly displayed as a table
      n_of_index_cols: 1
  - structure:
      tbl_name: "Structural"
      format: |
        <h4>PDB ID: <a href="https://www.rcsb.org/structure/{{ PDB_IDs }}">{{ PDB_IDs }}</a></h4>
        <div style="height: 400px; width: 100%; position: relative;" class='viewer_3Dmoljs' data-style='cartoon' data-pdb='{{ PDB_IDs }}'></div>
      n_of_index_cols: 0
  - active_site:
      tbl_name: "Active_Site"
      format: '' #Directly displayed as a table
      n_of_index_cols: 0
references:
  format: '<ul>
  <li class="ul-ul">{{ Reference }}</li>
  </ul>'
  n_of_index_cols: 1
addgene_references:
  format: | 
    <ul> 
      <li class="ul-ul">{{ Reference }} 
        <a href="{{ Addgene_link }}" target="_blank">
          <img src="/static/img/Addgene_Logo_plasmid.png" alt="addgene_link" style="border: .15rem solid #676774; border-radius: 10px; width: 3rem;"">
        </a>
      </li> 
    </ul>
  n_of_index_cols: 1

# <img src="/static/img/Addgene_Logo_plasmid.png" alt="addgene_link">