
# Database login instructions
username: "bellieny"
hostname: "localhost"
database_name: "caspedia"
port: 5432

# ********* GLOBAL CONFIGURATION *********
# Master table
source_metadata_path: ['2023_03_28_Cas_family_tree_Naming.csv']
# Wiki manifest containing URL for each and every wiki intake forms
wiki_manifest_path: "background_data/wiki_manifest.csv"

# DOI Internal database information
doi_table_name: 'doi_citation'

# Column in the main database that contains unique protein identifiers
unique_id_col: "Type Protein"

# ********* MASTER TABLE CONFIGURATION *********
# In-Database names of source tables
metadata_file_tags: ['master']
schema: "root"

# Main database table for user input search
default_search_table: "master"

# Column in the main database that contains aa sequence
sequence_col: "Protein sequence"

# ********* WIKI CONFIGURATION *********
# Wiki Pickle Directory path
pickles_path: "static/pkl"
# Wiki page formatting
wiki_template_path: "wiki_template.html"
# Wiki Sheets manifest
links_column: "Curation_Link"
wiki_schema_prefix: "wiki"
# Wiki association of table names between PSQL and intake forms
wiki_sections:
  - properties:
      tbl_name: "Properties"
      format: '<li><span style="color: #5758ff;font-weight: bold;">{{ Property }} </span>{{ Info }} {{ Citations }}</li>'
      n_of_index_cols: 1
  - resources:
      tbl_name: "Resources"
      format: '<li><span style="color: #5758ff;font-weight: bold;">{{ Resource }} </span>{{ Value }}</li>'
      n_of_index_cols: 1
  - text_summaries:
      tbl_name: "Text_Summaries"
      format: '<h3 class="section-header">{{ SECTION }}</h3>
    <p class="section-content">{{ CONTENT }}</p>'
      n_of_index_cols: 1
  - gene_editing_human:
      tbl_name: "Gene_Editing_Examples"
      format: '<h5>{{ Application_Type }}</h5>
               <ul>
                 <li class="ul-ul"> <i>In vivo</i> or <i>Ex vivo</i> Editing: <i>{{ In_Vivo_or_Ex_Vivo_Editing }}</i></li>
                 <li class="ul-ul"> Pharmaceutical or Product Name: {{ Pharmaceutical_or_Product_Name }}</li>
                 <li class="ul-ul"> NCT: {{ NCT }}</li>
                 <li class="ul-ul"> Responsible Party: {{ Responsible_Party }}</li>
                 <li class="ul-ul"> Description:</li>
                 <span>{{ Description }} {{ Citation_or_Publications }}</span>
             </ul>'
      n_of_index_cols: 1
  - gene_editing:
      tbl_name: "Gene_Editing_Examples"
      format: '<h5>{{ Application_Type }}</h5>
                 <ul>
                   <li class="ul-ul"> Description:</li>
                   <span>{{ Description }} {{ Citation_or_Publications }}</span>
                 </ul>'
      n_of_index_cols: 1
  - tools:
      tbl_name: "Tools_And_Diagnostics"
      format: '<h5>{{ Tool_Type }}</h5>
              <ul>
                  <li><span>{{ Tool_Name }}</span></li>
                <ul>
                  <li class="ul-ul"> Description:</li>
                  <span>{{ Description }} {{ Citation }}</span>
                </ul>
              </ul>'
      n_of_index_cols: 1
  - variants:
      tbl_name: "Engineered_Variants"
      format: '<h5>{{ Variant_Name }}</h5>
              <ul>
                <li class="ul-ul"> Description:</li>
                <span>{{ Description }}</span>
              </ul>'
      n_of_index_cols: 1
  - exp_details:
      tbl_name: "Experimental_Details"
      format: '<h5>{{ Tool_Type }}</h5>
              <ul>
                <li class="ul-ul"> Tool: {{ Tool }}</li>
                <li class="ul-ul"> Is the tool applicable: {{ Is_Tool_Applicable }}</li>
                <li class="ul-ul"> Notes: {{ Notes }} {{ Citation }}</li>
              </ul>'
      n_of_index_cols: 2
  - structure:
      tbl_name: "Structural"
      format: '<li><span style="color: #5758ff;font-weight: bold;">{{ Resource }}</span><a href="{{ Link }}" target="_blank"> {{ Value }}</a></li>'
      n_of_index_cols: 0
references:
  format: '<ul>
  <li class="ul-ul">{{ Reference }}</li>
  </ul>'
  n_of_index_cols: 1
