# BLASTP SPECIFIC CONFIGS
# The column in the blastout report to be used as
linked_column_sequence_search: "Hit_name"
linked_column_word_search: "Type Protein"

# WORD-SEARCH SPECIFIC CONFIGS
wordsearch_display_cols: ['Type Protein', 'Number',
                          'Type Protein Accession', 'Nuclease Activity Description',
                          'Targeting Requirement Description', 'Multiplexability Description', 'PAM']

# GENERAL RESULTS PAGE CONFIGS
# Temporary blastout table path
temp_blastout_dir: "jobs"

# Path to search page template
search_template_path: "templates/search_out_page.html"
# Path to search page template
wiki_template_path: "templates/wiki_template.html"

# Path to output search html page
dir_root_template_path: "templates"

# Internal temp directory for general html templates
temp_html_dir_path: "temp"
# Internal temp directory for wiki html templates
temp_wiki_dir_path: "wiki"

# Set the user-directed message for the user
sequence_search_message: "Deltablast results for"
word_search_message: "Word search results for"
