# BLASTP SPECIFIC CONFIGS
# The column in the blastout report to be used as
linked_column_sequence_search: "Hit_name"
linked_column_word_search: "Type Protein"

# Columns in the Blast result to be assigned as numeric
numeric_columns_blast: ["Query_length", "Hit_length",
                        "Blastp_alignment_length",
                        "Query_positives_cov_%",
                        "E-value"]

# Columns in the Master table that'll be appended to the Blast search result
columns_from_master: ["Type Protein", "Number", "PAM_or_PFS", "Class_II_Subtype"]

# WORD-SEARCH SPECIFIC CONFIGS
wordsearch_display_cols: ['Type Protein', 'Number',
                          'Protein_Accession', 'Nuclease_Activity',
                          'Targeting_Requirement', 'gRNA_and_Multiplexability', 'PAM_or_PFS']

# GENERAL RESULTS PAGE CONFIGS
# Temporary blastout table path
temp_blastout_dir: "jobs"

# Path to search page template
search_template_path: "templates/search_out_page.html"
# Path to search page template
wiki_template_path: "templates/wiki_template.html"

# Path to output search html page
dir_root_template_path: "templates"

# Internal temp directory for general html templates
temp_html_dir_path: "temp"
# Internal temp directory for wiki html templates
temp_wiki_dir_path: "wiki"

# Set the user-directed message for the user
sequence_search_message: "Deltablast results for"
word_search_message: "Word search results for"
